### ISSUE TITLE
Add troubleshooting instructions

### ISSUE THREAD

**Issue by p1gp1g** [UnifiedPush/documentation#33]
Many users do not have a fully configured setup (server-side or the distributor is not logged-in) and complain some app do not work

**Comment by p1gp1g** [comment]
1. Try **UP-Example**
if it works -> Troubleshot the app or ask for help on this app community
2. Trying to use **Gotify** ? Check twice it is **Gotify-UP** and not **Gotify** installed on your phone.
if it was **Gotify** -> install **Gotify-UP**
3. Try with *UP-FCM distributor** or **Gotify-UP** with an account on https://gotify1.unifiedpush.org/ (opened to registration)
if it works -> you have a problem on your setup : If you were trying to use **Gotify** : Have you set [the rewrite-proxy](https://unifiedpush.org/users/distributors/gotify/#self-hosting) ?

**Comment by karmanyaahm** [comment]
Would it be possible to somehow automate and add checking functionality into UP-Example or make a similar app called UP-Troubleshoot? It probably can't check all possible distributors, but it could check common ones like Gotify.

ie first check if distributor is installed and can send an endpoint
then does the endpoint work
if not, (assuming Gotify) does sending a Gotify type payload to /message instead of /UP work - if so, inform user that proxy is needed
etc etc

**Comment by p1gp1g** [comment]
Done
